import{api,h,inr}from'./api.js';const m=document.getElementById('m');
const E=e=>`<div class="msg e" role="alert">${h(e.message)}</div>`,T=(hd,rows)=>`<div class="scroll"><table><tr>${hd.map(x=>`<th>${x}</th>`).join('')}</tr>${rows.join('')}</table></div>`;
const NEXT={Pending:['Confirmed','Cancelled'],Confirmed:['Processing','Cancelled'],Processing:['Shipped','Cancelled'],Shipped:['Delivered']};
const V={
async dash(){const d=await api('/admin/dashboard'),o=d.orders;m.innerHTML=`<h1>Dashboard</h1><div class="grid">${[['Products',d.products],['Customers',d.customers],['Pending',o.Pending||0],['Processing',o.Processing||0],['Delivered',o.Delivered||0],['Low stock',d.lowStock],['Revenue (delivered only)',inr(d.revenue)]].map(([k,v])=>`<div class="box"><span class="mu">${k}</span><h2>${h(v)}</h2></div>`).join('')}</div>`},
async prod(){const p=await api('/admin/products');m.innerHTML=`<h1>Products</h1><form class="form box" id="pf"><input name="name" placeholder="Name" required><input name="brand" placeholder="Brand"><input name="category" placeholder="Category"><input name="sku" placeholder="SKU" required><input name="price" type="number" min="0" placeholder="Price" required><input name="mrp" type="number" min="0" placeholder="Original price"><input name="stock" type="number" min="0" placeholder="Stock" required><input name="images" placeholder="Image URL"><textarea name="desc" placeholder="Description"></textarea><div id="pe"></div><button>Add product</button></form>`+
 T(['Name','SKU','Price','Stock','Visible',''],p.map(x=>`<tr><td>${h(x.name)}</td><td>${h(x.sku)}</td><td><input type="number" min="0" value="${x.price}" data-f="price" data-id="${x._id}" style="width:100px"></td><td><input type="number" min="0" value="${x.stock}" data-f="stock" data-id="${x._id}" style="width:80px"></td><td>${x.active?'Yes':'Hidden'}</td><td><button class="ghost" data-del="${x._id}">Hide</button></td></tr>`));
 document.getElementById('pf').onsubmit=async e=>{e.preventDefault();try{await api('/admin/products',{method:'POST',body:Object.fromEntries(new FormData(e.target))});V.prod()}catch(er){document.getElementById('pe').innerHTML=E(er)}};
 m.querySelectorAll('[data-f]').forEach(i=>i.onchange=async()=>{try{await api('/admin/products/'+i.dataset.id,{method:'PATCH',body:{[i.dataset.f]:i.value}})}catch(er){alert(er.message);V.prod()}});
 m.querySelectorAll('[data-del]').forEach(b=>b.onclick=async()=>{if(confirm('Hide product from the store? Order history is kept.')){await api('/admin/products/'+b.dataset.del,{method:'DELETE'});V.prod()}})},
async ord(){const o=await api('/admin/orders');m.innerHTML='<h1>Orders</h1>'+T(['Order','Customer','Items','Total','Status','Update'],o.map(x=>`<tr><td>${h(x.number)}</td><td>${h(x.address.name)}<br><span class="mu">${h(x.address.phone)} · ${h(x.address.line)}, ${h(x.address.city)} ${h(x.address.pin)}</span></td><td>${x.items.map(i=>h(i.name)+' ×'+i.qty).join('<br>')}</td><td>${inr(x.total)}</td><td><span class="badge">${h(x.status)}</span></td><td>${(NEXT[x.status]||[]).map(s=>`<button class="ghost" data-id="${x._id}" data-s="${s}">${s}</button>`).join(' ')}</td></tr>`));
 m.querySelectorAll('[data-s]').forEach(b=>b.onclick=async()=>{try{await api('/admin/orders/'+b.dataset.id+'/status',{method:'PATCH',body:{status:b.dataset.s}});V.ord()}catch(er){alert(er.message)}})},
async cus(){const c=await api('/admin/customers');m.innerHTML='<h1>Customers</h1>'+T(['Name','Email','Phone','Joined'],c.map(x=>`<tr><td>${h(x.name)}</td><td>${h(x.email)}</td><td>${h(x.phone||'')}</td><td>${new Date(x.createdAt).toLocaleDateString()}</td></tr>`))}};
document.querySelectorAll('[data-t]').forEach(b=>b.onclick=()=>go(b.dataset.t));
async function go(t){try{await V[t]()}catch(e){m.innerHTML=E(e)+(e.status===401||e.status===403?'<a class="btn" href="/#/login">Login as admin</a>':'')}}go('dash');
